### ISSUE TITLE
Avatar: The Last Airbender doesn't work

### ISSUE THREAD

**Issue by rbowden91** [phiresky/tv-show-ratings#2]
Gives a javascript error in the console.

**Comment by melgu** [comment]
Same with _Star Wars: The Clone Wars_.

**Comment by phiresky** [comment]
To be honest, I'm not going to continue working on the current version, since IMDb is not updating the data set anymore. They now provide an alternate data set (partial implementation in v2 branch), but that data has a license that makes it illegal to be used for basically anything. Kind of ridiculous that they can do that since IMDb was originally a community forum with fully public access and 100% of the ratings data is provided by users - but apparently that's how it is now. 

I might implement a new version in a way that I don't have to host the actual data myself when I have time.

**Comment by phiresky** [comment]
I've finished v2 and merged it, which fixes this issue. Initial load might be slow since I'm no longer hosting the data myself.

https://phiresky.github.io/tv-show-ratings/?t=Avatar:_The_Last_Airbender_(2003-2008)+Star_Wars:_The_Clone_Wars_(2008-2019)
