### ISSUE TITLE
v2 doesn't work in Safari

### ISSUE THREAD

**Issue by melgu** [phiresky/tv-show-ratings#3]
The content doesn't load and I get a lot of error messages.
All are of the two variations below:

```
Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary

WebSocket network error: OSStatus Error -9806: connection closed via error 
```

**Comment by phiresky** [comment]
Sadly I don't have a Mac to test Safari right now - which makes this pretty hard to reproduce from here (and my macos vm broke a while ago). 

Might be related to https://github.com/feross/simple-peer/issues/190 - Safari apparently does not implement part of the WebRTC api. Which version of safari are you on?

Does https://webtorrent.io throw the same errors in console? (it might still appear to work since it also uses web seeds in addition to webrtc)

Edit: Two more related issues:
https://github.com/feross/simple-peer/issues/336
https://github.com/webtorrent/webtorrent/issues/1432

**Comment by melgu** [comment]
It does throw the same `… must be a dictionary` error. That site does work though.

**Comment by phiresky** [comment]
Looks like the upstream issue is already fixed - I'll pull the changes when the new version is released.

**Comment by phiresky** [comment]
Should be fixed now, I switched to the master version of simple-peer in 03deac2
@melgu , can you check if it works now? https://phiresky.github.io/tv-show-ratings

**Comment by melgu** [comment]
I get the following error for the Favicon, but otherwise it works as intended in Safari (macOS Mojave).
`Failed to load resource: the server responded with a status of 404 ()`
